name:  Terraform Plan/Apply for SBS Tech Hiring Challenge

on:
  push:
    branches: [ serverless-approach ]
  pull_request:
    branches: [ serverless-approach ]

jobs:
  PushToAWS:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: checkout feature branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform validate  
        run: terraform validate

      - run: terraform plan -out tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
      - if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
