name: Terraform Plan/Apply for SBS Tech Hiring Challenge

on:
  push:
    branches: [ serverless-approach ]
  pull_request:
    branches: [ serverless-approach ]

jobs:
  PushToAWS:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 
      - run: cd /Users/sujit/sbs-tech-hiring-challenge/terraform/

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform validate  
        run: terraform validate

      - run: terraform plan -out tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
      - if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
